### ISSUE TITLE
Version Webhook API To Support GraphQL alongside REST

### ISSUE THREAD

**Issue by shawalli** [bloomberg/python-github-webhook#13]
Currently, REST (v3) is the officially supported GitHubb API. v4 was debuted in September 2016; at that time, GitHub projected roughly a year of beta usage before going GA. 18 months later, v4 still isn't GA, but one would assume that it is coming very shortly. In order to get ahead of that coming version, this library should add a mechanism to support both versions, with the default being v3 for some time.

I don't have an architecture already sketched out, but I'm willing to help in whatever way needed to help support this effort.

**Comment by alexchamberlain** [comment]
My understanding of the Webhook interface from https://developer.github.com/webhooks/ is that it hasn't changed; the REST vs GraphQL affects the _pull_ API, rather than the _push_ API. Have I missed something?

**Comment by shawalli** [comment]
@alexchamberlain D'oh! You're right. I did see some GH devs talking about the possibility of graphql webhooks in the future, but not something that is currently supported. It also doesn't relate to the v3/v4 API.
