### ISSUE TITLE
Generalizing the Webhook class

### ISSUE THREAD

**Issue by srizzling** [bloomberg/python-github-webhook#6]
Is there someway we can generalize the webhook class so that we could use it in lambda or API gateway sense.

Was looking at perhaps using Chalice: https://github.com/aws/chalice/blob/master/chalice/app.py. Or should I just subclass and override the init method?

**Comment by fophillips** [comment]
I think it would just be a case of changing [this line](https://github.com/bloomberg/python-github-webhook/blob/70b2e23de8dcebba21da155926ae913afd32af0f/github_webhook/webhook.py#L20) to do whatever is needed for Chalice or whatever, rather than Flask. Is that what you mean?

**Comment by srizzling** [comment]
Yeah pretty much, but how do that without subclassing?

**Comment by fophillips** [comment]
Right now, yes, but I think it would be good - as you said - to generalise it in some way. Maybe by leaving it up to the app to add the rule, we could provide some helper functions for common frameworks. 

It will be a bit challenging to do this nicely and keep backwards compatibility but I'll have a think and CC you on the PR

**Comment by srizzling** [comment]
I'm happy to help out if you would like. Do you think this type of change has benefit for other users, or is just me being selfish about it. If its just me/my use case, then it might **not** be worth the risk.

**Comment by srizzling** [comment]
Any movement on this @fophillips, I'm not part of that team who managed this in my previous role, but it still might be helpful or else I'll just close this issue

**Comment by AstraLuma** [comment]
I would suggest using flask with either [awsgi](https://github.com/slank/awsgi) or [zappa](https://zappa.io).
